# /// script
# requires-python = ">=3.10,<3.13"
# dependencies = [
#     "kokoro>=0.9.4",
#     "misaki[en]>=0.9.4",
#     "transformers>=4.45",
#     "soundfile",
#     "numpy",
#     "en_core_web_sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl",
# ]
# ///
"""Record the site's spoken lines with natural-sounding voices.

Kokoro (https://huggingface.co/hexgrad/Kokoro-82M, Apache-2.0) runs on this computer and
reads every line listed by phrases.mjs, once per voice in speech.js's VOICES list. Each pack
(a training stage or an article) becomes one MP3 per voice in audio/voice/<voice>/, plus an
entry in js/voice-training.js / js/voice-articles.js saying where each line sits in it.
js/speech.js plays them; anything missing falls back to the browser's own voice.

    uv run scripts/voice/build.py            # record new or changed packs (needs uv, node, ffmpeg)
    python3 scripts/voice/build.py --check   # exit 1 if a pack is missing or out of date

Run it after changing articles, training stages, or a spoken line, then run
scripts/version-assets.py. Packs whose lines didn't change are kept as they are.
The first run downloads the voice model (~350 MB) into ~/.cache/huggingface.
"""
import argparse
import hashlib
import json
import pathlib
import re
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
AUDIO_DIR = ROOT / 'audio' / 'voice'
AUDIO_URL = '/audio/voice/'
CACHE_DIR = pathlib.Path.home() / '.cache' / 'typepets-voice'

SPEED = 1.0
SAMPLE_RATE = 24000
BITRATE = '48k'

GAP_MS = 120            # silence between lines in a pack's MP3
PRE_MS = 30             # each line's window starts this early and ends POST_MS late,
POST_MS = 60            # so a browser that shifts MP3 timing a little never clips a word
LAYOUT = 3              # bump when anything here changes how packs sound or are laid out

# Kokoro garbles very short input ("fox." comes out as "vox", "up." as "uppy"), so a line that
# is a single word is read as its own sentence after this one, then cut out (carrier_cut).
CARRIER = 'Here is the next word.'

# Letters said by name. Kokoro reads "A, left pinky" with the article "uh", so letter keys
# carry explicit phonemes (Kokoro's own, for each capital letter read on its own).
LETTER_PHONEMES = {
    'A': 'ˈA', 'B': 'bˈi', 'C': 'sˈi', 'D': 'dˈi', 'E': 'ˈi', 'F': 'ˈɛf', 'G': 'ʤˈi',
    'H': 'ˈAʧ', 'I': 'ˈI', 'J': 'ʤˈA', 'K': 'kˈA', 'L': 'ˈɛl', 'M': 'ˈɛm', 'N': 'ˈɛn',
    'O': 'ˈO', 'P': 'pˈi', 'Q': 'kjˈu', 'R': 'ˈɑɹ', 'S': 'ˈɛs', 'T': 'tˈi', 'U': 'jˈu',
    'V': 'vˈi', 'W': 'dˈʌbᵊlju', 'X': 'ˈɛks', 'Y': 'wˈI', 'Z': 'zˈi',
}

# Single words to say with these phonemes instead of Kokoro's (it reads "shall" unstressed,
# as in a sentence, which sounds like "shl" on its own).
PRONOUNCE = {'shall': 'ʃˈæl'}

# Lines that came out unclear in one voice (found by a Whisper listening check): record a
# different take. Bump the number to try another.
RETAKES = {('af_bella', '<G>.'): 1}

MANIFEST_RE = re.compile(r'/\*json\*/(.*)/\*end\*/', re.S)
MANIFEST_HEADER = '''/**
 * Recorded voice packs. Per pack: the spoken lines (clip keys) and, per voice, the MP3 and
 * where each line sits in it (`at`: start ms, length ms, in the order of `keys`).
 * Generated by scripts/voice/build.py. Do not edit by hand.
 */
'''


def load_phrases():
    out = subprocess.run(['node', str(ROOT / 'scripts' / 'voice' / 'phrases.mjs')],
                         check=True, capture_output=True, text=True).stdout
    return json.loads(out)


def synth_text(script):
    """What Kokoro reads for a line: letters (and PRONOUNCE words) as explicit phonemes."""
    word = script.rstrip('.')
    if word.lower() in PRONOUNCE:
        return f'[{word}](/{PRONOUNCE[word.lower()]}/).'
    return re.sub(r'<([A-Z])>', lambda m: f'[{m.group(1)}](/{LETTER_PHONEMES[m.group(1)]}/)', script)


def pack_sig(clips, voice):
    lines = [[c['key'], synth_text(c['script']), RETAKES.get((voice, c['script']), 0)] for c in clips]
    blob = json.dumps([LAYOUT, voice, SPEED, BITRATE, CARRIER, lines], ensure_ascii=False)
    return hashlib.sha256(blob.encode()).hexdigest()[:16]


def read_manifest(rel):
    path = ROOT / rel
    if not path.is_file():
        return {}
    m = MANIFEST_RE.search(path.read_text(encoding='utf-8'))
    return json.loads(m.group(1)) if m else {}


def write_manifest(rel, packs):
    body = json.dumps(packs, ensure_ascii=False, separators=(',', ':'))
    text = (MANIFEST_HEADER +
            f'window.VOICE_PACKS = Object.assign(window.VOICE_PACKS || {{}}, /*json*/{body}/*end*/);\n')
    (ROOT / rel).write_text(text, encoding='utf-8')


def voice_entry(manifest, name, voice):
    return ((manifest.get(name) or {}).get('voices') or {}).get(voice)


def is_current(entry, sig):
    return bool(entry) and entry.get('sig') == sig and \
        (AUDIO_DIR / entry['src'].removeprefix(AUDIO_URL)).is_file()


# ─── Recording ────────────────────────────────────────────────

class Recorder:
    def __init__(self):
        import numpy as np
        import soundfile as sf
        import torch
        from kokoro import KPipeline
        self.np, self.sf, self.torch = np, sf, torch
        self.pipeline = KPipeline(lang_code='a', repo_id='hexgrad/Kokoro-82M')

    def raw(self, script, voice):
        """Kokoro's audio for one line (float32, 24 kHz), cached on disk. A single word comes back
        still inside the carrier phrase, with the timings needed to cut it out (else None)."""
        single = len(script.split()) == 1
        text = synth_text(script)
        if single:
            text = f'{CARRIER} {text}'
        take = RETAKES.get((voice, script), 0)
        key = ('full|' if single else '') + text + (f'|take {take}' if take else '')
        digest = hashlib.sha256(key.encode()).hexdigest()[:20]
        path = CACHE_DIR / f'{voice}-{SPEED}' / f'{digest}.wav'
        timing_path = path.with_suffix('.json')
        if path.is_file() and (timing_path.is_file() or not single):
            audio, _ = self.sf.read(path, dtype='float32')
            return audio, json.loads(timing_path.read_text()) if single else None
        self.torch.manual_seed(int(digest[:8], 16))  # same line, same take
        results = [r for r in self.pipeline(text, voice=voice, speed=SPEED) if r.audio is not None]
        if not results:
            raise RuntimeError(f'Kokoro produced no audio for {script!r}')
        audio = self.np.concatenate([r.audio.numpy() for r in results]).astype('float32')
        timing = self.carrier_timing(results, script) if single else None
        path.parent.mkdir(parents=True, exist_ok=True)
        self.sf.write(path, audio, SAMPLE_RATE, subtype='FLOAT')
        if single:
            timing_path.write_text(json.dumps(timing))
        return audio, timing

    def carrier_timing(self, results, script):
        """When CARRIER's last word ends and when the word after it starts, per Kokoro."""
        if len(results) == 1:
            tokens = results[0].tokens or []
            dot = next((i for i, t in enumerate(tokens) if t.text == '.'), None)
            if dot is not None:
                before = [t for t in tokens[:dot] if t.phonemes and t.end_ts is not None]
                word = next((t for t in tokens[dot + 1:] if t.phonemes and t.start_ts is not None), None)
                if before and word:
                    return {'gap': before[-1].end_ts, 'word': word.start_ts}
        raise RuntimeError(f'Could not find {script!r} after the carrier sentence')

    def carrier_cut(self, audio, timing):
        """Where to cut the word out: the quietest moment between the carrier and the word.
        Kokoro's timings are only roughly right and some voices barely pause, so a fixed offset
        either keeps the end of "word" or clips the word's first sound. Of the frames within
        3 dB of the quietest, the last one wins, so nothing of the carrier is left before it."""
        np = self.np
        frame = ms(5)
        lo = max(0, int((timing['gap'] - 0.03) * SAMPLE_RATE))
        hi = max(lo + frame, int((timing['word'] + 0.015) * SAMPLE_RATE))
        n = (hi - lo) // frame
        rms = np.sqrt(np.mean(audio[lo:lo + n * frame].reshape(n, frame) ** 2, axis=1)) + 1e-9
        near_min = np.nonzero(rms <= rms.min() * 10 ** (3 / 20))[0]
        return lo + int(near_min[-1]) * frame

    def clip(self, script, voice):
        """Trimmed, evenly loud, with soft edges."""
        np = self.np
        audio, carrier = self.raw(script, voice)
        if carrier:
            audio = audio[self.carrier_cut(audio, carrier):]
        peak = float(np.max(np.abs(audio))) or 1.0
        # Low threshold and generous margins keep quiet sounds like the f in "fox" or a final t
        loud = np.nonzero(np.abs(audio) > max(0.002, peak * 0.01))[0]
        start = max(0, loud[0] - ms(30))
        end = min(len(audio), loud[-1] + ms(80))
        audio = audio[start:end].copy()

        frames = audio[: len(audio) // ms(20) * ms(20)].reshape(-1, ms(20))
        rms = np.sqrt(np.mean(frames ** 2, axis=1))
        voiced = rms[rms > 10 ** (-45 / 20)]
        level = float(np.mean(voiced)) if len(voiced) else float(np.sqrt(np.mean(audio ** 2)))
        gain = min(10 ** (-18 / 20) / max(level, 1e-6), 0.95 / peak)
        audio *= gain

        fade = min(ms(5), len(audio) // 2)
        ramp = np.linspace(0, 1, fade, dtype='float32')
        audio[:fade] *= ramp
        audio[-fade:] *= ramp[::-1]
        return audio


def ms(n):
    return SAMPLE_RATE * n // 1000


def build_pack(recorder, name, clips, voice):
    np = recorder.np
    gap = np.zeros(ms(GAP_MS), dtype='float32')
    pieces = [gap]
    pos = len(gap)
    at = []
    for c in clips:
        audio = recorder.clip(c['script'], voice)
        at += [round(pos * 1000 / SAMPLE_RATE) - PRE_MS,
               round(len(audio) * 1000 / SAMPLE_RATE) + PRE_MS + POST_MS]
        pieces += [audio, gap]
        pos += len(audio) + len(gap)

    pcm = np.concatenate(pieces).astype('<f4').tobytes()
    folder = AUDIO_DIR / voice
    folder.mkdir(parents=True, exist_ok=True)
    tmp = folder / f'.{name}.tmp.mp3'
    subprocess.run(['ffmpeg', '-hide_banner', '-loglevel', 'error', '-y',
                    '-f', 'f32le', '-ar', str(SAMPLE_RATE), '-ac', '1', '-i', '-',
                    '-c:a', 'libmp3lame', '-b:a', BITRATE, '-map_metadata', '-1',
                    '-fflags', '+bitexact', '-flags:a', '+bitexact', str(tmp)],
                   input=pcm, check=True)
    digest = hashlib.sha256(tmp.read_bytes()).hexdigest()[:8]
    final = folder / f'{name}.{digest}.mp3'
    tmp.replace(final)
    return final, at


# ─── Main ─────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    parser.add_argument('--check', action='store_true', help='only report missing or stale packs')
    args = parser.parse_args()

    phrases = load_phrases()
    voices = phrases['voices']
    files = phrases['files']
    stale = [(rel, name, voice) for rel, packs in files.items()
             for name, clips in packs.items() for voice in voices
             if not is_current(voice_entry(read_manifest(rel), name, voice), pack_sig(clips, voice))]

    if args.check:
        for rel, name, voice in stale:
            print(f'{rel}: {name} ({voice}) needs recording')
        extra = [rel for rel, packs in files.items()
                 if any(name not in packs or set(entry.get('voices', {})) - set(voices)
                        for name, entry in read_manifest(rel).items())]
        for rel in extra:
            print(f'{rel}: has packs or voices that no longer exist')
        if stale or extra:
            print('Run: uv run scripts/voice/build.py')
            return 1
        print('Voice packs are up to date.')
        return 0

    for tool in ('node', 'ffmpeg'):
        if not shutil.which(tool):
            sys.exit(f'{tool} is needed but not installed')
    AUDIO_DIR.mkdir(parents=True, exist_ok=True)
    recorder = Recorder() if stale else None

    for rel, packs in files.items():
        old = read_manifest(rel)
        new = {}
        for name, clips in packs.items():
            entry = new[name] = {'keys': [c['key'] for c in clips], 'voices': {}}
            for voice in voices:
                sig = pack_sig(clips, voice)
                current = voice_entry(old, name, voice)
                if is_current(current, sig):
                    entry['voices'][voice] = current
                    continue
                path, at = build_pack(recorder, name, clips, voice)
                entry['voices'][voice] = {'src': AUDIO_URL + path.relative_to(AUDIO_DIR).as_posix(),
                                          'sig': sig, 'at': at}
                print(f'{voice} {name}: {len(clips)} lines, {path.stat().st_size // 1024} KB')
        write_manifest(rel, new)

    keep = {v['src'].removeprefix(AUDIO_URL)
            for rel in files for pack in read_manifest(rel).values() for v in pack['voices'].values()}
    for path in sorted(AUDIO_DIR.rglob('*.mp3')):
        if path.relative_to(AUDIO_DIR).as_posix() not in keep:
            path.unlink()
            print(f'removed {path.relative_to(AUDIO_DIR)}')
    for folder in AUDIO_DIR.iterdir():
        if folder.is_dir() and not any(folder.iterdir()):
            folder.rmdir()

    for voice in voices:
        size = sum(p.stat().st_size for p in (AUDIO_DIR / voice).glob('*.mp3'))
        print(f'{voice}: {size / 1e6:.1f} MB')
    return 0


if __name__ == '__main__':
    sys.exit(main())
